# Descripción de la plataforma  {.unnumbered}

<br>

La base de datos del SNIRA está estructurada en cuatro secciones que comprenden 88 campos, de los cuales 33 son campos obligatorios marcados con un asterisco (<span style="color:red">\*</span>) que incluyen datos acerca de la información general del proyecto, las personas e instituciones involucradas, información relevante sobre diversos aspectos sociales y ambientales y fuentes de información. 

En la medida de lo posible, los campos de captura incluyen catálogos de vocabulario controlado para estandarizar la información ingresada en la base de datos. La lista de nombres de especies proviene de los Catálogos de Autoridades Taxonómicas del Sistema Nacional de Información sobre Biodiversidad de México (<https://www.snib.mx/>) para evitar posibles errores en su escritura, así como para identificar sinonimias. Las referencias bibliográficas que permiten respaldar la información de la base de datos están directamente vinculadas con los proyectos. A la fecha, se han recopilado 1,600 documentos enfocados al tema de la restauración en México, publicados a partir de 1990. Los documentos incluyen libros, secciones de libros, artículos de revistas científicas y de divulgación, informes, tesis, entre varios otros documentos. La información de estas publicaciones está en proceso de ser capturada en la base de datos. 

La información capturada en el SNIRA será revisada por el equipo de trabajo a cargo del SNIRA en la Conabio para evitar inconsistencias y asegurar en la medida de lo posible la calidad de los datos. Una vez que el proyecto haya sido revisado y aprobado, la información estará disponible para su consulta por parte del público en general.


**Si tiene dudas, comentarios sobre el sistema o problemas de navegación, por favor escriba a snira@conabio.gob.mx**.
