# Subsección 2.2: Instituciones involucradas en el proyecto {.unnumbered}

La subsección comprende seis campos; si agrega una institución, __tres de los campos son obligatorios (*)__. 

### Tipo de iniciativa*
El tipo de iniciativa se refiere al liderazgo para desarrollar un proyecto de restauración. 
Seleccione todas las opciones que correspondan:
    - Academia: Proyecto propuesto o realizado por personas docentes, personas investigadoras universitarias de instituciones educativas, personas investigadoras de instituciones no educativas.
    - Comunitaria: Proyecto propuesto por comunidades indígenas o rurales de México.
    - Privada: Proyecto propuesto o realizado por una iniciativa privada, por ejemplo por el Grupo Bimbo o CEMEX.
    - Pública: Proyecto propuesto o realizado por una iniciativa pública. Por ejemplo, aplica para proyectos en colaboración con la Comisión Nacional de Áreas Nacionales Protegidas (CONANP) o la Comisión Nacional Forestal (CONAFOR).
    - Organización de la sociedad civil: Proyecto propuesto o realizado por la iniciativa social.
    - Otra: Seleccione cuando el tipo de iniciativa no aparece en la lista.
    - No determinado: Seleccione cuando no es posible identificar el tipo de iniciativa.
    - No aplica: Seleccione cuando ninguna de las otras opciones aplica. 

### Tipo de colaboración*
El tipo de colaboración se refiere a la participación o esfuerzo individual o colectivo entre personas, instituciones o países de desarrollar un proyecto de restauración; el tipo de colaboración está determinado por el alcance geográfico y la escala espacial de los objetivos establecidos en los proyectos.

Seleccione la opción que corresponda:
    - Local: en una localidad, ciudad o barrios; entre una o más comunidades, ejidos, o municipios. Los recursos suelen venir de fuentes locales, como el gobierno municipal, organizaciones sin fines de lucro o donaciones privadas.
    - Regional: en una región más amplia que puede comprender uno o varios  estados, cuencas geográficas o provincias. Los recursos pueden provenir de fuentes estatales o federales u organizaciones internacionales.
    - Nacional: proyecto de gran alcance en México . Los recursos para un proyecto nacional suelen provenir de varias instituciones, incl. el gobierno federal,  organizaciones internacionales, corporaciones multinacionales y donaciones privadas.
    - Binacional: entre instituciones de dos países, p. ej., instituciones de México y Estados Unidos.
    - Multinacional: entre instituciones de más de dos países, p. ej., instituciones de México,  Estados Unidos y Alemania.
    - No determinado: Seleccione cuando no es posible identificar el tipo de iniciativa.
    - No aplica: Seleccione cuando ninguna de las otras opciones aplica.

### Pulse __‘Agregar institución +’__ 
para que se desplieguen los campos y pueda capturar los datos. Si no cuenta con información, puede saltarse esta parte. 
__Si su proyecto se ubica en un área protegida, por favor agregue a la Comisión Nacional de Áreas Nacionales Protegidas.__
Pulse ‘Eliminar’ sino va a capturar información.

#### Institución que participó / participa / participará en el proyecto*
Seleccione una opción de la lista; puede empezar a escribir el nombre para que aparezcan opciones con nombre similares. 
Podrá agregar tantas instituciones como desee a través del mismo botón. 
En caso de no encontrar la institución deseada, seleccione la opción de ‘----’ al inicio de la lista. 

#### En caso de no encontrar la institución, por favor indique el nombre.
Campo de texto abierto que permite introducir el nombre de la institución y su dependencia, p. ej., Colegio de Postgraduados, Campus Montecillo, Instituto de Recursos Naturales, Laboratorio de Etnobotánica. 

#### Tipo de responsabilidad*
Seleccione las opciones de la lista que correspondan.
Seleccione ‘No determinado’ si no cuenta con la información. 
Seleccione ‘No aplica’ cuando ninguna de las otras opciones aplica.

### Comentarios respecto a las instituciones involucradas
Campo de texto abierto que permite introducir comentarios, opiniones, etc. respecto a las instituciones involucradas.

### GUARDAR
**Pulse el botón ‘Guardar’, una vez que haya registrado los datos.**
En el caso de que todos los campos obligatorios hayan sido llenados, el sistema arrojará una ventana con la leyenda 'Cambios guardados'. Pulse el botón ‘Aceptar’ para asegurar que la información sea guardada en el sistema. 
Pulse el botón ‘Siguiente’ para pasar a la siguiente sección. 
Si algún campo obligatorio se encuentra vacío, el botón ‘Guardar’ estará deshabilitado. 


