#    Subsección 3.3: Actividades del proyecto {.unnumbered}

La subsección comprende siete campos; **un campo es estrictamente obligatorio (<span style="color:red">\*</span>)**.

### Indique los métodos o técnicas que se usaron / usan / usarán para el proyecto de restauración
Escriba los métodos o técnicas usadas en el proyecto, p. ej., caracterización de hábitat, análisis de crecimiento, trasplante de fragmentos de corales, recolección de lluvia de semillas de árboles, observación de aves, encuesta, modelación de la distribución potencial de especies, identificación de sitios prioritarios para la restauración, meta-análisis, entre varios otros. Si copia información del documento, póngala entre comillas " " para indicar que es una cita textual. Si la información está en un idioma distinto al español, favor de traducir.

### Actividades de restauración*
Seleccione todas las opciones de la lista que correspondan. 
Seleccione ‘No determinado’ cuando no es posible determinar las actividades de restauración.
Seleccione ‘No aplica’ cuando ninguna de las otras opciones aplica.


### Otras actividades de restauración
Escriba las actividades de restauración si no aparecen en el catálogo o quiera dar más detalles, p. ej., adición de acolchados, llenado de cárcavas, reforestación con especies medicinales nativas de la región.

### Indicadores de monitoreo
El monitoreo se refiere a una actividad crítica que implica la recolección continua y análisis de información que permite supervisar, evaluar y dar seguimiento a un proyecto en relación a sus objetivos y metas.

Pulse el botón ‘Agregar indicador de monitoreo +’ para que se desplieguen los campos y pueda capturar los datos. Si no cuenta con información, puede saltarse esta parte. 
Podrá agregar tantos sitios como desee a través del mismo botón. 
Pulse ‘Eliminar’ sino va a capturar información.

#### Indicador de monitoreo*
Seleccione la opción de la lista que corresponda.
Seleccione ‘No determinado’ cuando no es posible determinar el indicador.
Seleccione ‘No aplica’ cuando ninguna de las otras opciones aplica.
 

#### Objeto de monitoreo*
Seleccione la opción de la lista que corresponda.
Seleccione ‘No determinado’ cuando no es posible determinar el objeto.
Seleccione ‘No aplica’ cuando ninguna de las otras opciones aplica.

### Otras actividades de monitoreo
Escriba las actividades de monitoreo si no aparecen en el catálogo o quiera dar más detalles, p. ej., el monitoreo de aves durante la temporada seca y de lluvias.

### Comentarios respecto a las actividades de restauración o monitoreo.
Campo de texto abierto que permite introducir comentarios, opiniones, etc. respecto a las actividades de restauración y/o monitoreo que considera importantes indicar.

### GUARDAR
Pulse el botón ‘Guardar’, una vez que haya registrado los datos.
En el caso de que todos los campos obligatorios hayan sido llenados, el sistema arrojará una ventana con la leyenda 'Cambios guardados'. Pulse el botón ‘Aceptar’ para asegurar que la información sea guardada en el sistema. 

Pulse el botón ‘Siguiente’ para pasar a la siguiente subsección. 
Si algún campo obligatorio se encuentra vacío, el botón ‘Guardar’ estará deshabilitado. 
