#    Resultados y conclusiones  {.unnumbered}

La subsección comprende dos campos; ninguno es obligatorio.

### Resultados generales del proyecto{.unnumbered}
Escriba brevemente los principales resultados del proyecto.

Si copia información del documento, póngala entre comillas " " para indicar que es una cita textual. Si la información está en un idioma distinto al español, favor de traducir.

Si aún no cuenta con resultados, deje el campo vacío.


### Conclusiones generales del proyecto{.unnumbered}
Escriba brevemente las principales conclusiones del proyecto, incluye lecciones aprendidas, detección de vacíos de información.

Si copia información del documento, póngala entre comillas " " para indicar que es una cita textual. Si la información está en un idioma distinto al español, favor de traducir.

Si aún no cuenta con conclusiones o lecciones aprendidas, deje el campo vacío.


### GUARDAR{.unnumbered}

**Pulse el botón ‘Guardar’, una vez que haya registrado los datos**.

En el caso de que todos los campos obligatorios hayan sido llenados, el sistema abrirá una ventana con la leyenda 'Cambios guardados'. Pulse el botón ‘Aceptar’ para asegurar que la información haya sido guardada en el sistema. Si no se abre la ventana, vuelva a presionar el botón ´Guardar´ al menos dos veces más.

Pulse el botón ‘Siguiente’ para pasar a la siguiente sección. 

Si algún campo obligatorio se encuentra vacío, el botón ‘Guardar’ estará deshabilitado.

