# Fuentes de información {.unnumbered}

La subsección comprende dos campos; ninguno es obligatorio.

### Referencia{.unnumbered}
Escriba el apellido o título de la referencia; no use acentos ni tildes, p. ej., escriba Perez Gomez en vez de Pérez-Gómez. 

Al teclear la palabra, aparecerá una lista de 10 opciones que se actualiza conforme se sigue tecleando. 

Las referencias están integradas en y vinculadas al gestor bibliográfico de Zotero, manejado por la CONABIO. Actualmente, contiene casi 1,600 documentos, incluyendo artículos de revistas científicas y de divulgación, capítulo de libros, informes, tesis, entre otros que fueron publicados a partir de 1990.

### Referencia nueva{.unnumbered}
En caso que no encuentre una referencia en la lista, por favor, escriba la referencia en formato APA. 

Si no cuenta con una publicación, puede incluir la referencia de otra evidencia disponible en línea, p. ej., video o documental. 
En caso de no contar con algún material de referencia, escriba: Observación personal.

Puede utilizar el generador de citas [Scribbr](https://www.scribbr.es/citar/generador/), que por medio del URL (sitio web, vídeo o artículo de noticias en línea), DOI (Artículo de revista) o   ISBN (libro) realiza la búsqueda y el despliegue de la referencia en formato APA.

Consulte las [Normas APA 7.^a^edición](https://www.revista.unam.mx/wp-content/uploads/3_Normas-APA-7-ed-2019-11-6.pdf)este documento** para más información y ejemplos de la estructura del formato APA.

    - Artículo: Apellido, A.A. y Autor/a, B.B. (año de la publicación). Título del artículo. Título de la revista, Volumen (Número), Páginas (xx-xx). https://doi.org/xxx o http://xxx.
    - Libro: Editor/a, E. E. y Editor/a, F. F. (eds.) (año de la publicación). Título del libro (edición). Editorial.
    - Capítulo de libro: Apellido, A.A. del capítulo (año de la publicación). Título del capítulo. En Editor del libro (ed.). Título del libro (pp. xx-xx). Editorial.
    - Tesis: Apellido, A.A. (año de la publicación). Título de la tesis. Tesis de (grado académico). Institución de donde es egresado el autor o la autora. 
    - Informe: Apellido, A.A. (año de la publicación). Título del informe. Editorial. https://doi.org/xxx o http://xxx.


### GUARDAR y terminar{.unnumbered}
**Podrá editar la información las veces que sean necesarias mientras su proyecto esté en estatus ‘Edición’**, que puede ver en la sección 1: Información general, ubicado en la parte superior. Una vez que pulse el botón ‘Enviar a revisión mi proyecto’ que se encuentra al final de las cuatro secciones, es decir después la sección 4: Fuentes de información, automáticamente el estatus del proyecto cambiará a ‘En revisión’ y ya no será posible hacer cambios, al menos que haya campos obligatorios vacíos o el sistema encuentra inconsistencias en los datos capturados. Si requiere hacer algún cambio después de haber enviado el proyecto a revisión, deberá enviar un correo electrónico a **snira@conabio.gob.mx**.

Pulse ‘Enviar para revisión’ cuando haya registrado toda la información.

El sistema abrirá una ventana ‘Enviar a revisión mi proyecto’. Por favor, lea cuidadosamente el contenido de la ventana. 

Si todos los campos obligatorios han sido llenados, se habilitará el botón ‘Enviar’. Al pulsarlo, el sistema guardará su proyecto, y la información será revisada por el equipo de trabajo de la Conabio. 

En el caso de que exista algún campo obligatorio vacío, el sistema le avisará en que sección se encuentra y podrá completar la información. Una vez que haya llenado la información requerida, vuelva a pulsar el botón ‘Enviar para revisión’ para habilitar el botón ‘Enviar’. 

Una vez enviada la información, será redirigida*o a la ventana de inicio en donde podrá agregar más proyectos o consultar información de otros proyectos. 
**La información de su proyecto estará disponible para la consulta del público en general cuando los datos hayan sido revisados por el equipo de trabajo de la Conabio y fue registrada en la base de datos del SNIRA, por lo que el estatus del proyecto será ‘REGISTRADO’.**
