# Enviar proyecto a revisión  {.unnumbered}

<br>

### GUARDAR {.unnumbered}
<<<<<<< HEAD
**Podrá editar la información las veces que sean necesarias mientras su proyecto esté en estatus ‘Edición’**, el cual se puede ver en la sección 1: Información general, ubicado en la parte superior. Una vez que pulse el botón ‘Enviar para revisión’, el cual se encuentra al final de las cuatro secciones, es decir después la sección 4: Fuentes de información, el estatus del proyecto cambiará automáticamente a ‘En revisión’ y ya no será posible hacer cambios, al menos que haya campos obligatorios vacíos o el sistema encuentra inconsistencias en los datos capturados. Si requiere hacer algún cambio después de haber enviado el proyecto a revisión, deberá enviar un correo electrónico a **snira@conabio.gob.mx**.
=======

**Podrá editar la información las veces que sean necesarias mientras su proyecto esté en estatus ‘Edición’**, el cuál se puede ver en la sección 1: Información general, ubicado en la parte superior. Una vez que pulse el botón ‘Enviar para revisión’, el cuál se encuentra al final de las cuatro secciones, es decir después la sección 4: Fuentes de información, el estatus del proyecto cambiará automáticamente a ‘En revisión’ y ya no será posible hacer cambios, al menos que haya campos obligatorios vacíos o el sistema encuentra inconsistencias en los datos capturados. Si requiere hacer algún cambio después de haber enviado el proyecto a revisión, deberá enviar un correo electrónico a **snira@conabio.gob.mx**.
>>>>>>> 3242884524047490fa2dde1c0f0a95fd4fb93ed9


### Enviar {.unnumbered}

Pulse **‘Enviar para revisión’ cuando haya registrado toda la información**.


El sistema abrirá una ventana ‘Enviar a revisión’. Por favor, lea cuidadosamente el contenido de la ventana. 


Si todos los campos obligatorios han sido llenados, se habilitará el botón ‘Enviar’. Al pulsarlo, el sistema guardará su proyecto, y la información será revisada por el equipo de trabajo de la Conabio. 

En el caso de que exista algún campo obligatorio vacío, el sistema le avisará en que sección se encuentra y podrá completar la información. Una vez que haya llenado la información requerida, vuelva a pulsar el botón ‘Enviar para revisión’ para habilitar el botón ‘Enviar’. 

Una vez enviada la información, se abrirá la ventana de inicio en donde podrá agregar más proyectos o consultar información de otros proyectos. 

**La información de su proyecto estará disponible para la consulta del público en general cuando los datos hayan sido revisados por el equipo de trabajo de la Conabio y fue registrada en la base de datos del SNIRA, por lo que el estatus del proyecto será ‘REGISTRADO’.**

